-- Wrap auth/session function calls in RLS policy predicates in (SELECT ...) so Postgres
-- evaluates them once per statement (InitPlan) instead of once per row -- the
-- Supabase-documented RLS perf pattern. Predicate-equivalent (row visibility unchanged).
-- Generated by 'pgrls fix --rule PERF001' and verified (PERF001 -> 0). Refs #906.

-- [PERF001] Wrap auth function call(s) in policy 'Authenticated users can read audit_logs' on public.audit_logs so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Authenticated users can read audit_logs" ON public.audit_logs
    USING ((SELECT auth.role()) = CAST('authenticated' AS text));

-- [PERF001] Wrap auth function call(s) in policy 'Service role has full access to audit_logs' on public.audit_logs so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Service role has full access to audit_logs" ON public.audit_logs
    USING ((SELECT auth.role()) = CAST('service_role' AS text));

-- [PERF001] Wrap auth function call(s) in policy 'Admins can write categories' on public.categories so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Admins can write categories" ON public.categories
    USING ((SELECT current_setting(CAST('jwt.claims.role' AS text), TRUE)) = CAST('admin' AS text));
