import type { Project } from '~/lib/types/project'

export const projects: Project[] = [
	{
		id: '1',
		title: 'Empowering Education',
		description:
			'Support education programs for children in low-income areas. Together, we can bridge the education gap and create opportunities.',
		image: '/images/education.webp',
		categoryId: '7',
		goal: 55000,
		raised: 40000,
		investors: 40,
		minInvestment: 10,
		tags: ['EDUCATION', 'CHILDREN', 'FUTURE'],
	},
	{
		id: '2',
		title: 'Forest Restoration Initiative',
		description:
			'Restore and reforest areas devastated by uncontrolled deforestation. Your support helps rebuild ecosystems and fight climate change.',
		image: '/images/bosques.webp',
		categoryId: '3',
		goal: 60000,
		raised: 54000,
		investors: 35,
		minInvestment: 10,
		tags: ['ENVIRONMENT', 'ECOLOGICAL', 'SUSTAINABLE'],
	},
	{
		id: '3',
		title: 'Mobile Clinics',
		description:
			'Bring essential healthcare services to remote areas through mobile clinics. Your support helps save lives and build healthier communities.',
		image: '/images/healthcare.webp',
		categoryId: '8',
		goal: 45000,
		raised: 32000,
		investors: 30,
		minInvestment: 20,
		tags: ['HEALTHCARE', 'COMMUNITY', 'IMPACT'],
	},
	{
		id: '4',
		title: 'Preserving Indigenous Crafts',
		description:
			'Support the preservation of indigenous craftsmanship in Costa Rica. Your contributions protect traditional techniques and cultural heritage.',
		image: '/images/artesania.webp',
		categoryId: '5',
		goal: 50000,
		raised: 34000,
		investors: 29,
		minInvestment: 15,
		tags: ['CULTURE', 'INDIGENOUS', 'ART'],
	},
	{
		id: '5',
		title: 'Water for Rural Communities',
		description:
			'Provide access to safe drinking water in underserved rural areas. Help us install water purification systems to improve health and livelihoods.',
		image: '/images/water.webp',
		categoryId: '6',
		goal: 40000,
		raised: 28000,
		investors: 45,
		minInvestment: 5,
		tags: ['WATER', 'HEALTH', 'COMMUNITY'],
	},
	{
		id: '6',
		title: 'Rural Animal Shelter',
		description:
			'Provide care and shelter to homeless animals in rural communities. Help us create safe havens for animals in need.',
		image: '/images/dogs.webp',
		categoryId: '1',
		goal: 70000,
		raised: 45000,
		investors: 60,
		minInvestment: 10,
		tags: ['ANIMALS', 'CARE', 'COMMUNITY'],
	},
	{
		id: '7',
		title: 'Community Garden Project',
		description:
			'Transform vacant urban spaces into thriving community gardens. Help us create green spaces that provide fresh food and bring people together.',
		image: '/images/placeholder.png',
		categoryId: '10',
		goal: 25000,
		raised: 18000,
		investors: 32,
		minInvestment: 5,
		tags: ['COMMUNITY', 'FOOD', 'URBAN'],
	},
	{
		id: '8',
		title: 'Natural Disasters Human Aid',
		description:
			'Provide critical support to communities affected by natural disasters. From emergency supplies to long-term rebuilding efforts, join us in bringing hope and recovery to those in need.',
		image: '/images/disaster-aid.webp',
		categoryId: '4',
		goal: 100000,
		raised: 82000,
		investors: 120,
		minInvestment: 10,
		tags: ['EMERGENCY', 'RELIEF', 'HUMANITARIAN'],
	},
	{
		id: '9',
		title: 'Healthy Kids Workshop',
		description:
			'Provide nourishing meals and support to children at risk of malnutrition in Costa Rica. Together, we can ensure a brighter future for every child.',
		image: '/images/kids.webp',
		categoryId: '2',
		goal: 35000,
		raised: 22000,
		investors: 28,
		minInvestment: 15,
		tags: ['CHILDREN', 'NUTRITION', 'NGO'],
	},
	{
		id: '10',
		title: 'Renewable Energy for Schools',
		description:
			'Install solar panels in underfunded schools to reduce costs and teach sustainability. Help us bring clean energy to education.',
		image: '/images/placeholder.png',
		categoryId: '9',
		goal: 80000,
		raised: 56000,
		investors: 42,
		minInvestment: 20,
		tags: ['ENERGY', 'EDUCATION', 'SUSTAINABILITY'],
	},
	{
		id: '11',
		title: 'Animal Shelter Expansion',
		description:
			'Help us expand our animal shelter to rescue more abandoned pets. Your support provides food, medical care, and loving homes.',
		image: '/images/placeholder.png',
		categoryId: '11',
		goal: 45000,
		raised: 31000,
		investors: 55,
		minInvestment: 5,
		tags: ['ANIMALS', 'RESCUE', 'CARE'],
	},
	{
		id: '12',
		title: 'Local Journalism Fund',
		description:
			'Support independent journalism in underserved communities. Help us keep citizens informed and hold power accountable.',
		image: '/images/placeholder.png',
		categoryId: '12',
		goal: 30000,
		raised: 17000,
		investors: 25,
		minInvestment: 10,
		tags: ['MEDIA', 'DEMOCRACY', 'INFORMATION'],
	},
	{
		id: '13',
		title: 'Urban Farming Initiative',
		description:
			'Transform unused urban spaces into productive community farms. Help us create sustainable food sources in city environments.',
		image: '/images/placeholder.png',
		categoryId: '3',
		goal: 35000,
		raised: 12000,
		investors: 28,
		minInvestment: 10,
		tags: ['AGRICULTURE', 'SUSTAINABILITY', 'COMMUNITY'],
	},
	{
		id: '14',
		title: 'Mental Health Support Network',
		description:
			'Build a network of mental health professionals providing free services to underserved communities. Support mental wellbeing for all.',
		image: '/images/placeholder.png',
		categoryId: '8',
		goal: 60000,
		raised: 38000,
		investors: 52,
		minInvestment: 15,
		tags: ['HEALTH', 'MENTAL', 'SUPPORT'],
	},
	{
		id: '15',
		title: 'Clean Ocean Initiative',
		description:
			'Remove plastic waste from our oceans and develop sustainable alternatives to single-use plastics. Help us protect marine life.',
		image: '/images/placeholder.png',
		categoryId: '3',
		goal: 75000,
		raised: 48000,
		investors: 67,
		minInvestment: 20,
		tags: ['OCEAN', 'ENVIRONMENT', 'PLASTIC'],
	},
	{
		id: '16',
		title: 'Accessible Technology for All',
		description:
			'Develop assistive technologies for people with disabilities. Help make the digital world accessible to everyone.',
		image: '/images/placeholder.png',
		categoryId: '10',
		goal: 50000,
		raised: 29000,
		investors: 38,
		minInvestment: 15,
		tags: ['TECHNOLOGY', 'ACCESSIBILITY', 'INCLUSION'],
	},
	{
		id: '17',
		title: 'Refugee Education Program',
		description:
			'Provide educational resources and support for refugee children. Help them build a brighter future through learning.',
		image: '/images/placeholder.png',
		categoryId: '7',
		goal: 40000,
		raised: 27000,
		investors: 42,
		minInvestment: 10,
		tags: ['EDUCATION', 'REFUGEES', 'CHILDREN'],
	},
	{
		id: '18',
		title: 'Sustainable Housing Solutions',
		description:
			'Build eco-friendly, affordable housing for low-income families. Help create sustainable communities for the future.',
		image: '/images/placeholder.png',
		categoryId: '3',
		goal: 90000,
		raised: 62000,
		investors: 75,
		minInvestment: 25,
		tags: ['HOUSING', 'SUSTAINABILITY', 'COMMUNITY'],
	},
	{
		id: '19',
		title: 'Arts Education for Youth',
		description:
			'Bring arts education to underserved schools. Help nurture creativity and self-expression in young people.',
		image: '/images/placeholder.png',
		categoryId: '5',
		goal: 30000,
		raised: 18000,
		investors: 32,
		minInvestment: 10,
		tags: ['ARTS', 'EDUCATION', 'YOUTH'],
	},
	{
		id: '20',
		title: 'Senior Companion Program',
		description:
			'Connect elderly individuals with companions to reduce isolation and improve quality of life. Help combat loneliness in our senior population.',
		image: '/images/placeholder.png',
		categoryId: '10',
		goal: 25000,
		raised: 16000,
		investors: 28,
		minInvestment: 5,
		tags: ['SENIORS', 'COMPANIONSHIP', 'COMMUNITY'],
	},
]
