version: "3"

tasks:
  # ? Task to install dependencies for all packages
  install:
    desc: "Install dependencies for all packages"
    cmds:
      - bun run init
    silent: true

  # ? Task to clean node_modules in all packages
  clean:
    desc: "Clean node_modules in all packages"
    cmds:
      - bun run clean

  # ? Task to format and lint the codebase
  lint:
    desc: "Format and lint the codebase"
    cmds:
      - bun run format-and-lint

  # ? Task to fix formatting and linting issues
  lint:fix:
    desc: "Fix formatting and linting issues"
    cmds:
      - bun run format-and-lint:fix

  # ? Task to run the development server for the web app
  web:dev:
    desc: "Run the development server for the web app"
    cmds:
      - cd apps/web && bun dev

  # ? Task to build the web app
  web:build:
    desc: "Build the web app"
    cmds:
      - cd apps/web && bun run build

  # ? Task to start the production server for the web app
  web:start:
    desc: "Start the production server for the web app"
    cmds:
      - cd apps/web && bun run start

  # ? Task to generate types and schemas for the Supabase service
  supabase:gen:
    desc: "Generate types and schemas for the Supabase service"
    cmds:
      - cd services/supabase && bun run gen

  # ? Task to generate types and schemas for the Local Supabase service
  supabase:gen-local:
    desc: "Generate types and schemas for the Local Supabase service"
    cmds:
      - cd services/supabase && bun run gen:local

  # ? Indexer tasks
  indexer:build:
    desc: "Build the Subquery Indexer"
    cmds:
      - cd apps/indexer && bun run build

  indexer:build-dev:
    desc: "Build the Subquery Indexer"
    cmds:
      - cd apps/indexer && bun run build:develop

  indexer:codegen:
    desc: "Generate code for the Subquery Indexer"
    cmds:
      - cd apps/indexer && bun run codegen

  indexer:prepack:
    desc: "Prepare the Subquery Indexer for packaging"
    cmds:
      - cd apps/indexer && bun prepack

  indexer:dev:
    desc: "Run the Subquery Indexer in development mode"
    cmds:
      - cd apps/indexer && bun dev

  indexer:start-docker:
    desc: "Start the Subquery Indexer in a Docker container with an indexer, PostgreSQL DB, and a query service"
    cmds:
      - cd apps/indexer && bun start:docker

  # ? Academy Web App tasks
  academy:dev:
    desc: "Run the development server for the Academy web app"
    cmds:
      - cd apps/academy-wep && bun dev

  academy:build:
    desc: "Build the Academy web app"
    cmds:
      - cd apps/academy-wep && bun run build

  academy:start:
    desc: "Start the production server for the Academy web app"
    cmds:
      - cd apps/academy-wep && bun run start

  academy:test:
    desc: "Run tests for the Academy web app"
    cmds:
      - cd apps/academy-wep && bun test

  # ? AI Service tasks
  ai:dev:
    desc: "Run the AI service in development mode"
    cmds:
      - cd services/ai && bun start

  ai:test:
    desc: "Run tests for the AI service"
    cmds:
      - cd services/ai && bun test
