import type { Project } from '~/lib/types/projects.types'

export const mockProjectsView: Project[] = [
	{
		id: '1',
		title: 'Empowering Education',
		description:
			'Support education programs for children in low-income areas. Together, we can bridge the educational gap.',
		image_url: '/images/education.webp',
		categories: ['education'],
		current_amount: 40000,
		target_amount: 55000,
		investors_count: 40,
		min_investment: 10,
		tags: ['EDUCATION', 'CHILDREN', 'FUTURE'],
		created_at: '2023-12-01T00:00:00Z',
		milestones: 0,
		completedMilestones: (40000 / 55000) * 100,
		creator: {
			id: 1,
			name: 'John Doe',
			image: '/images/nft8.png',
			verified: true,
			completedProjects: 5,
		},
		featured: false,
		trending: false,
	},
	{
		id: '2',
		title: 'Mobile Clinics',
		description:
			'Bring essential healthcare services to remote areas through mobile clinics. Your support saves lives.',
		image_url: '/images/healthcare.webp',
		categories: ['healthcare'],
		current_amount: 32000,
		target_amount: 45000,
		investors_count: 30,
		min_investment: 20,
		tags: ['HEALTHCARE', 'COMMUNITY', 'IMPACT'],
		created_at: '2023-11-15T00:00:00Z',
		milestones: 0,
		completedMilestones: (40000 / 55000) * 100,
		creator: {
			id: 1,
			name: 'John Doe',
			image: '/images/nft8.png',
			verified: true,
			completedProjects: 5,
		},
		featured: false,
		trending: false,
	},
	{
		id: '3',
		title: 'Healthy Kids Workshop',
		description:
			'Provide nourishing meals and support to children at risk of malnutrition in Costa Rica.',
		image_url: '/images/kids.webp',
		categories: ['healthcare', 'children'],
		current_amount: 22800,
		target_amount: 25000,
		investors_count: 18,
		min_investment: 5,
		tags: ['NGO', 'NUTRITION', 'CHILDREN'],
		created_at: '2023-10-15T00:00:00Z',
		milestones: 0,
		completedMilestones: (40000 / 55000) * 100,
		creator: {
			id: 1,
			name: 'John Doe',
			image: '/images/nft8.png',
			verified: true,
			completedProjects: 5,
		},
		featured: false,
		trending: false,
	},
	{
		id: '4',
		title: 'Forest Restoration Initiative',
		description:
			'Restore and reforest areas devastated by uncontrolled deforestation. Your support matters.',
		image_url: '/images/bosques.webp',
		categories: ['sustainability', 'climate'],
		current_amount: 54000,
		target_amount: 60000,
		investors_count: 35,
		min_investment: 10,
		tags: ['ENVIRONMENT', 'ECOLOGICAL', 'SUSTAINABLE'],
		created_at: '2023-11-01T00:00:00Z',
		milestones: 0,
		completedMilestones: (40000 / 55000) * 100,
		creator: {
			id: 1,
			name: 'John Doe',
			image: '/images/nft8.png',
			verified: true,
			completedProjects: 5,
		},
		featured: false,
		trending: false,
	},
	{
		id: '5',
		title: 'Disaster Aid Response',
		description:
			'Provide immediate aid and support to communities affected by natural disasters.',
		image_url: '/images/disaster-aid.webp',
		categories: ['community', 'healthcare'],
		current_amount: 28500,
		target_amount: 40000,
		investors_count: 55,
		min_investment: 5,
		tags: ['EMERGENCY', 'AID', 'RELIEF'],
		created_at: '2023-09-22T00:00:00Z',
		milestones: 0,
		completedMilestones: (40000 / 55000) * 100,
		creator: {
			id: 1,
			name: 'John Doe',
			image: '/images/nft8.png',
			verified: true,
			completedProjects: 5,
		},
		featured: false,
		trending: false,
	},
	{
		id: '6',
		title: 'Artisan Community Support',
		description:
			'Help local artisans preserve traditional crafts and expand their market reach.',
		image_url: '/images/artesania.webp',
		categories: ['community', 'education'],
		current_amount: 15200,
		target_amount: 30000,
		investors_count: 42,
		min_investment: 15,
		tags: ['CRAFTS', 'HERITAGE', 'COMMUNITY'],
		created_at: '2023-12-05T00:00:00Z',
		milestones: 0,
		completedMilestones: (40000 / 55000) * 100,
		creator: {
			id: 1,
			name: 'John Doe',
			image: '/images/nft8.png',
			verified: true,
			completedProjects: 5,
		},
		featured: false,
		trending: false,
	},
	{
		id: '7',
		title: 'Sustainable E-commerce Platform',
		description:
			'Build an online marketplace connecting eco-friendly producers with conscious consumers.',
		image_url: '/images/ecommerce.webp',
		categories: ['sustainability', 'community'],
		current_amount: 67000,
		target_amount: 100000,
		investors_count: 89,
		min_investment: 25,
		tags: ['ECOMMERCE', 'SUSTAINABILITY', 'BUSINESS'],
		created_at: '2023-10-30T00:00:00Z',
		milestones: 0,
		completedMilestones: (40000 / 55000) * 100,
		creator: {
			id: 1,
			name: 'John Doe',
			image: '/images/nft8.png',
			verified: true,
			completedProjects: 5,
		},
		featured: false,
		trending: false,
	},
	{
		id: '8',
		title: 'Animal Rescue Center',
		description:
			'Create a sanctuary for abandoned and injured animals, providing care and rehabilitation.',
		image_url: '/images/dogs.webp',
		categories: ['community', 'healthcare'],
		current_amount: 18300,
		target_amount: 25000,
		investors_count: 73,
		min_investment: 5,
		tags: ['ANIMALS', 'RESCUE', 'WELFARE'],
		created_at: '2023-11-20T00:00:00Z',
		milestones: 0,
		completedMilestones: (40000 / 55000) * 100,
		creator: {
			id: 1,
			name: 'John Doe',
			image: '/images/nft8.png',
			verified: true,
			completedProjects: 5,
		},
		featured: false,
		trending: false,
	},
]
