import type { Project } from '~/lib/types/projects.types';

export const mockProjectsView: Project[] = [
  {
    id: '1',
    title: 'Empowering Education',
    description:
      'Support education programs for children in low-income areas. Together, we can bridge the educational gap.',
    image: '/images/education.webp',
    categories: ['education'],
    currentAmount: 40000,
    targetAmount: 55000,
    investors: 40,
    minInvestment: 10,
    tags: ['EDUCATION', 'CHILDREN', 'FUTURE'],
    createdAt: '2023-12-01T00:00:00Z',
    milestones: 0,
    completedMilestones: (40000 / 55000) * 100,
    creator: {
      id: 1,
      name: 'John Doe',
      image: '/images/nft8.png',
      verified: true,
      completedProjects: 5,
    },
    featured: false,
    trending: false,
  },
  {
    id: '2',
    title: 'Mobile Clinics',
    description:
      'Bring essential healthcare services to remote areas through mobile clinics. Your support saves lives.',
    image: '/images/healthcare.webp',
    categories: ['healthcare'],
    currentAmount: 32000,
    targetAmount: 45000,
    investors: 30,
    minInvestment: 20,
    tags: ['HEALTHCARE', 'COMMUNITY', 'IMPACT'],
    createdAt: '2023-11-15T00:00:00Z',
    milestones: 0,
    completedMilestones: (40000 / 55000) * 100,
    creator: {
      id: 1,
      name: 'John Doe',
      image: '/images/nft8.png',
      verified: true,
      completedProjects: 5,
    },
    featured: false,
    trending: false,
  },
  {
    id: '3',
    title: 'Healthy Kids Workshop',
    description:
      'Provide nourishing meals and support to children at risk of malnutrition in Costa Rica.',
    image: '/images/kids.webp',
    categories: ['healthcare', 'children'],
    currentAmount: 22800,
    targetAmount: 25000,
    investors: 18,
    minInvestment: 5,
    tags: ['NGO', 'NUTRITION', 'CHILDREN'],
    createdAt: '2023-10-15T00:00:00Z',
    milestones: 0,
    completedMilestones: (40000 / 55000) * 100,
    creator: {
      id: 1,
      name: 'John Doe',
      image: '/images/nft8.png',
      verified: true,
      completedProjects: 5,
    },
    featured: false,
    trending: false,
  },
  {
    id: '4',
    title: 'Forest Restoration Initiative',
    description:
      'Restore and reforest areas devastated by uncontrolled deforestation. Your support matters.',
    image: '/images/bosques.webp',
    categories: ['sustainability', 'climate'],
    currentAmount: 54000,
    targetAmount: 60000,
    investors: 35,
    minInvestment: 10,
    tags: ['ENVIRONMENT', 'ECOLOGICAL', 'SUSTAINABLE'],
    createdAt: '2023-11-01T00:00:00Z',
    milestones: 0,
    completedMilestones: (40000 / 55000) * 100,
    creator: {
      id: 1,
      name: 'John Doe',
      image: '/images/nft8.png',
      verified: true,
      completedProjects: 5,
    },
    featured: false,
    trending: false,
  },
  {
    id: '5',
    title: 'Disaster Aid Response',
    description:
      'Provide immediate aid and support to communities affected by natural disasters.',
    image: '/images/disaster-aid.webp',
    categories: ['community', 'healthcare'],
    currentAmount: 28500,
    targetAmount: 40000,
    investors: 55,
    minInvestment: 5,
    tags: ['EMERGENCY', 'AID', 'RELIEF'],
    createdAt: '2023-09-22T00:00:00Z',
    milestones: 0,
    completedMilestones: (40000 / 55000) * 100,
    creator: {
      id: 1,
      name: 'John Doe',
      image: '/images/nft8.png',
      verified: true,
      completedProjects: 5,
    },
    featured: false,
    trending: false,
  },
  {
    id: '6',
    title: 'Artisan Community Support',
    description:
      'Help local artisans preserve traditional crafts and expand their market reach.',
    image: '/images/artesania.webp',
    categories: ['community', 'education'],
    currentAmount: 15200,
    targetAmount: 30000,
    investors: 42,
    minInvestment: 15,
    tags: ['CRAFTS', 'HERITAGE', 'COMMUNITY'],
    createdAt: '2023-12-05T00:00:00Z',
    milestones: 0,
    completedMilestones: (40000 / 55000) * 100,
    creator: {
      id: 1,
      name: 'John Doe',
      image: '/images/nft8.png',
      verified: true,
      completedProjects: 5,
    },
    featured: false,
    trending: false,
  },
  {
    id: '7',
    title: 'Sustainable E-commerce Platform',
    description:
      'Build an online marketplace connecting eco-friendly producers with conscious consumers.',
    image: '/images/ecommerce.webp',
    categories: ['sustainability', 'community'],
    currentAmount: 67000,
    targetAmount: 100000,
    investors: 89,
    minInvestment: 25,
    tags: ['ECOMMERCE', 'SUSTAINABILITY', 'BUSINESS'],
    createdAt: '2023-10-30T00:00:00Z',
    milestones: 0,
    completedMilestones: (40000 / 55000) * 100,
    creator: {
      id: 1,
      name: 'John Doe',
      image: '/images/nft8.png',
      verified: true,
      completedProjects: 5,
    },
    featured: false,
    trending: false,
  },
  {
    id: '8',
    title: 'Animal Rescue Center',
    description:
      'Create a sanctuary for abandoned and injured animals, providing care and rehabilitation.',
    image: '/images/dogs.webp',
    categories: ['community', 'healthcare'],
    currentAmount: 18300,
    targetAmount: 25000,
    investors: 73,
    minInvestment: 5,
    tags: ['ANIMALS', 'RESCUE', 'WELFARE'],
    createdAt: '2023-11-20T00:00:00Z',
    milestones: 0,
    completedMilestones: (40000 / 55000) * 100,
    creator: {
      id: 1,
      name: 'John Doe',
      image: '/images/nft8.png',
      verified: true,
      completedProjects: 5,
    },
    featured: false,
    trending: false,
  },
];
