import type { Project } from '~/lib/types/projects.types'

export const mockProjectsView: Project[] = [
	{
		id: '1',
		title: 'Empowering Education',
		description:
			'Support education programs for children in low-income areas. Together, we can bridge the educational gap.',
		imageUrl: '/images/education.webp',
		categories: ['education'],
		currentAmount: 40000,
		goalAmount: 55000,
		supporters: 40,
		minSupport: 10,
		tags: ['EDUCATION', 'CHILDREN', 'FUTURE'],
		createdAt: '2023-12-01T00:00:00Z',
	},
	{
		id: '2',
		title: 'Mobile Clinics',
		description:
			'Bring essential healthcare services to remote areas through mobile clinics. Your support saves lives.',
		imageUrl: '/images/healthcare.webp',
		categories: ['healthcare'],
		currentAmount: 32000,
		goalAmount: 45000,
		supporters: 30,
		minSupport: 20,
		tags: ['HEALTHCARE', 'COMMUNITY', 'IMPACT'],
		createdAt: '2023-11-15T00:00:00Z',
	},
	{
		id: '3',
		title: 'Healthy Kids Workshop',
		description:
			'Provide nourishing meals and support to children at risk of malnutrition in Costa Rica.',
		imageUrl: '/images/kids.webp',
		categories: ['healthcare', 'children'],
		currentAmount: 22800,
		goalAmount: 25000,
		supporters: 18,
		minSupport: 5,
		tags: ['NGO', 'NUTRITION', 'CHILDREN'],
		createdAt: '2023-10-15T00:00:00Z',
	},
	{
		id: '4',
		title: 'Forest Restoration Initiative',
		description:
			'Restore and reforest areas devastated by uncontrolled deforestation. Your support matters.',
		imageUrl: '/images/bosques.webp',
		categories: ['sustainability', 'climate'],
		currentAmount: 54000,
		goalAmount: 60000,
		supporters: 35,
		minSupport: 10,
		tags: ['ENVIRONMENT', 'ECOLOGICAL', 'SUSTAINABLE'],
		createdAt: '2023-11-01T00:00:00Z',
	},
	{
		id: '5',
		title: 'Disaster Aid Response',
		description:
			'Provide immediate aid and support to communities affected by natural disasters.',
		imageUrl: '/images/disaster-aid.webp',
		categories: ['community', 'healthcare'],
		currentAmount: 28500,
		goalAmount: 40000,
		supporters: 55,
		minSupport: 5,
		tags: ['EMERGENCY', 'AID', 'RELIEF'],
		createdAt: '2023-09-22T00:00:00Z',
	},
	{
		id: '6',
		title: 'Artisan Community Support',
		description:
			'Help local artisans preserve traditional crafts and expand their market reach.',
		imageUrl: '/images/artesania.webp',
		categories: ['community', 'education'],
		currentAmount: 15200,
		goalAmount: 30000,
		supporters: 42,
		minSupport: 15,
		tags: ['CRAFTS', 'HERITAGE', 'COMMUNITY'],
		createdAt: '2023-12-05T00:00:00Z',
	},
	{
		id: '7',
		title: 'Sustainable E-commerce Platform',
		description:
			'Build an online marketplace connecting eco-friendly producers with conscious consumers.',
		imageUrl: '/images/ecommerce.webp',
		categories: ['sustainability', 'community'],
		currentAmount: 67000,
		goalAmount: 100000,
		supporters: 89,
		minSupport: 25,
		tags: ['ECOMMERCE', 'SUSTAINABILITY', 'BUSINESS'],
		createdAt: '2023-10-30T00:00:00Z',
	},
	{
		id: '8',
		title: 'Animal Rescue Center',
		description:
			'Create a sanctuary for abandoned and injured animals, providing care and rehabilitation.',
		imageUrl: '/images/dogs.webp',
		categories: ['community', 'healthcare'],
		currentAmount: 18300,
		goalAmount: 25000,
		supporters: 73,
		minSupport: 5,
		tags: ['ANIMALS', 'RESCUE', 'WELFARE'],
		createdAt: '2023-11-20T00:00:00Z',
	},
]
