// Generated by ts-to-zod
import { z } from "zod";
import { Json } from "./database.types";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const auditLogsRowSchema = z.object({
  actor_id: z.string().nullable(),
  correlation_id: z.string(),
  created_at: z.string().nullable(),
  duration_ms: z.number().nullable(),
  error_code: z.string().nullable(),
  id: z.string(),
  metadata: jsonSchema.nullable(),
  operation: z.string(),
  resource_id: z.string().nullable(),
  resource_type: z.string(),
  status: z.string(),
});

export const auditLogsInsertSchema = z.object({
  actor_id: z.string().optional().nullable(),
  correlation_id: z.string(),
  created_at: z.string().optional().nullable(),
  duration_ms: z.number().optional().nullable(),
  error_code: z.string().optional().nullable(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  operation: z.string(),
  resource_id: z.string().optional().nullable(),
  resource_type: z.string(),
  status: z.string(),
});

export const auditLogsUpdateSchema = z.object({
  actor_id: z.string().optional().nullable(),
  correlation_id: z.string().optional(),
  created_at: z.string().optional().nullable(),
  duration_ms: z.number().optional().nullable(),
  error_code: z.string().optional().nullable(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  operation: z.string().optional(),
  resource_id: z.string().optional().nullable(),
  resource_type: z.string().optional(),
  status: z.string().optional(),
});

export const categoriesRowSchema = z.object({
  color: z.string(),
  id: z.string(),
  name: z.string(),
  slug: z.string().nullable(),
});

export const categoriesInsertSchema = z.object({
  color: z.string(),
  id: z.string().optional(),
  name: z.string(),
  slug: z.string().optional().nullable(),
});

export const categoriesUpdateSchema = z.object({
  color: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  slug: z.string().optional().nullable(),
});

export const challengesRowSchema = z.object({
  challenge: z.string(),
  created_at: z.string(),
  expires_at: z.string(),
  id: z.string(),
  identifier: z.string(),
  next_auth_user_id: z.string().nullable(),
  rp_id: z.string(),
  user_id: z.string().nullable(),
});

export const challengesInsertSchema = z.object({
  challenge: z.string(),
  created_at: z.string().optional(),
  expires_at: z.string().optional(),
  id: z.string().optional(),
  identifier: z.string(),
  next_auth_user_id: z.string().optional().nullable(),
  rp_id: z.string(),
  user_id: z.string().optional().nullable(),
});

export const challengesUpdateSchema = z.object({
  challenge: z.string().optional(),
  created_at: z.string().optional(),
  expires_at: z.string().optional(),
  id: z.string().optional(),
  identifier: z.string().optional(),
  next_auth_user_id: z.string().optional().nullable(),
  rp_id: z.string().optional(),
  user_id: z.string().optional().nullable(),
});

export const commentTypeSchema = z.union([
  z.literal("comment"),
  z.literal("question"),
  z.literal("answer"),
]);

export const commentsInsertSchema = z.object({
  author_id: z.string(),
  content: z.string(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  metadata: jsonSchema.optional(),
  parent_comment_id: z.string().optional().nullable(),
  project_id: z.string().optional().nullable(),
  project_update_id: z.string().optional().nullable(),
  type: commentTypeSchema.optional(),
  updated_at: z.string().optional().nullable(),
});

export const commentsUpdateSchema = z.object({
  author_id: z.string().optional(),
  content: z.string().optional(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  metadata: jsonSchema.optional(),
  parent_comment_id: z.string().optional().nullable(),
  project_id: z.string().optional().nullable(),
  project_update_id: z.string().optional().nullable(),
  type: commentTypeSchema.optional(),
  updated_at: z.string().optional().nullable(),
});

export const communityRowSchema = z.object({
  comment_id: z.string(),
  created_at: z.string().nullable(),
  id: z.string(),
  project_id: z.string(),
  update_id: z.string(),
});

export const communityInsertSchema = z.object({
  comment_id: z.string(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  project_id: z.string(),
  update_id: z.string(),
});

export const communityUpdateSchema = z.object({
  comment_id: z.string().optional(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  project_id: z.string().optional(),
  update_id: z.string().optional(),
});

export const contributionsRowSchema = z.object({
  amount: z.number(),
  contributor_id: z.string(),
  created_at: z.string().nullable(),
  id: z.string(),
  project_id: z.string(),
  updated_at: z.string().nullable(),
});

export const contributionsInsertSchema = z.object({
  amount: z.number(),
  contributor_id: z.string(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  project_id: z.string(),
  updated_at: z.string().optional().nullable(),
});

export const contributionsUpdateSchema = z.object({
  amount: z.number().optional(),
  contributor_id: z.string().optional(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  project_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const backupStateSchema = z.union([
  z.literal("not_backed_up"),
  z.literal("backed_up"),
]);

export const deviceTypeSchema = z.union([
  z.literal("single_device"),
  z.literal("multi_device"),
]);

export const profileVerificationStatusSchema = z.union([
  z.literal("unverified"),
  z.literal("verified"),
]);

export const escrowStatusTypeSchema = z.union([
  z.literal("NEW"),
  z.literal("FUNDED"),
  z.literal("ACTIVE"),
  z.literal("COMPLETED"),
  z.literal("DISPUTED"),
  z.literal("CANCELLED"),
]);

export const escrowContractsInsertSchema = z.object({
  amount: z.number(),
  completed_at: z.string().optional().nullable(),
  contract_id: z.string(),
  contribution_id: z.string(),
  created_at: z.string().optional().nullable(),
  current_state: escrowStatusTypeSchema.optional(),
  engagement_id: z.string(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  payer_address: z.string(),
  platform_fee: z.number(),
  project_id: z.string(),
  receiver_address: z.string(),
  updated_at: z.string().optional().nullable(),
});

export const escrowContractsUpdateSchema = z.object({
  amount: z.number().optional(),
  completed_at: z.string().optional().nullable(),
  contract_id: z.string().optional(),
  contribution_id: z.string().optional(),
  created_at: z.string().optional().nullable(),
  current_state: escrowStatusTypeSchema.optional(),
  engagement_id: z.string().optional(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  payer_address: z.string().optional(),
  platform_fee: z.number().optional(),
  project_id: z.string().optional(),
  receiver_address: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const escrowMilestonesRowSchema = z.object({
  created_at: z.string(),
  escrow_id: z.string(),
  milestone_id: z.string(),
  updated_at: z.string(),
});

export const escrowMilestonesInsertSchema = z.object({
  created_at: z.string().optional(),
  escrow_id: z.string(),
  milestone_id: z.string(),
  updated_at: z.string().optional(),
});

export const escrowMilestonesUpdateSchema = z.object({
  created_at: z.string().optional(),
  escrow_id: z.string().optional(),
  milestone_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const escrowReviewsRowSchema = z.object({
  created_at: z.string().nullable(),
  disputer_id: z.string().nullable(),
  escrow_id: z.string(),
  evidence_urls: z.array(z.string()).nullable(),
  id: z.string(),
  milestone_id: z.string().nullable(),
  resolution_text: z.string().nullable(),
  review_notes: z.string().nullable(),
  reviewed_at: z.string().nullable(),
  reviewer_address: z.string(),
  status: z.string(),
  transaction_hash: z.string().nullable(),
  type: z.string(),
});

export const escrowReviewsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  disputer_id: z.string().optional().nullable(),
  escrow_id: z.string(),
  evidence_urls: z.array(z.string()).optional().nullable(),
  id: z.string().optional(),
  milestone_id: z.string().optional().nullable(),
  resolution_text: z.string().optional().nullable(),
  review_notes: z.string().optional().nullable(),
  reviewed_at: z.string().optional().nullable(),
  reviewer_address: z.string(),
  status: z.string().optional(),
  transaction_hash: z.string().optional().nullable(),
  type: z.string(),
});

export const escrowReviewsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  disputer_id: z.string().optional().nullable(),
  escrow_id: z.string().optional(),
  evidence_urls: z.array(z.string()).optional().nullable(),
  id: z.string().optional(),
  milestone_id: z.string().optional().nullable(),
  resolution_text: z.string().optional().nullable(),
  review_notes: z.string().optional().nullable(),
  reviewed_at: z.string().optional().nullable(),
  reviewer_address: z.string().optional(),
  status: z.string().optional(),
  transaction_hash: z.string().optional().nullable(),
  type: z.string().optional(),
});

export const escrowStatusRowSchema = z.object({
  current_milestone: z.number().nullable(),
  escrow_id: z.string(),
  id: z.string(),
  last_updated: z.string().nullable(),
  metadata: jsonSchema.nullable(),
  status: escrowStatusTypeSchema,
  total_funded: z.number().nullable(),
  total_released: z.number().nullable(),
});

export const escrowStatusInsertSchema = z.object({
  current_milestone: z.number().optional().nullable(),
  escrow_id: z.string(),
  id: z.string().optional(),
  last_updated: z.string().optional().nullable(),
  metadata: jsonSchema.optional().nullable(),
  status: escrowStatusTypeSchema,
  total_funded: z.number().optional().nullable(),
  total_released: z.number().optional().nullable(),
});

export const escrowStatusUpdateSchema = z.object({
  current_milestone: z.number().optional().nullable(),
  escrow_id: z.string().optional(),
  id: z.string().optional(),
  last_updated: z.string().optional().nullable(),
  metadata: jsonSchema.optional().nullable(),
  status: escrowStatusTypeSchema.optional(),
  total_funded: z.number().optional().nullable(),
  total_released: z.number().optional().nullable(),
});

export const foundationEscrowsRowSchema = z.object({
  created_at: z.string(),
  escrow_id: z.string(),
  foundation_id: z.string(),
  updated_at: z.string(),
});

export const foundationEscrowsInsertSchema = z.object({
  created_at: z.string().optional(),
  escrow_id: z.string(),
  foundation_id: z.string(),
  updated_at: z.string().optional(),
});

export const foundationEscrowsUpdateSchema = z.object({
  created_at: z.string().optional(),
  escrow_id: z.string().optional(),
  foundation_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const foundationMilestonesRowSchema = z.object({
  achieved_date: z.string(),
  created_at: z.string(),
  description: z.string().nullable(),
  foundation_id: z.string(),
  id: z.string(),
  impact_metric: z.string().nullable(),
  metadata: jsonSchema.nullable(),
  title: z.string(),
  updated_at: z.string(),
});

export const foundationMilestonesInsertSchema = z.object({
  achieved_date: z.string(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  foundation_id: z.string(),
  id: z.string().optional(),
  impact_metric: z.string().optional().nullable(),
  metadata: jsonSchema.optional().nullable(),
  title: z.string(),
  updated_at: z.string().optional(),
});

export const foundationMilestonesUpdateSchema = z.object({
  achieved_date: z.string().optional(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  foundation_id: z.string().optional(),
  id: z.string().optional(),
  impact_metric: z.string().optional().nullable(),
  metadata: jsonSchema.optional().nullable(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
});

export const creatorEntityTypeSchema = z.union([
  z.literal("individual"),
  z.literal("ngo"),
  z.literal("foundation"),
]);

export const foundationsInsertSchema = z.object({
  cover_image_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  description: z.string(),
  entity_type: creatorEntityTypeSchema.optional(),
  founded_year: z.number(),
  founder_id: z.string(),
  id: z.string().optional(),
  logo_url: z.string().optional().nullable(),
  metadata: jsonSchema.optional(),
  mission: z.string().optional().nullable(),
  name: z.string(),
  slug: z.string(),
  social_links: jsonSchema.optional(),
  total_campaigns_completed: z.number().optional(),
  total_campaigns_open: z.number().optional(),
  total_donations_received: z.number().optional(),
  updated_at: z.string().optional(),
  vision: z.string().optional().nullable(),
  website_url: z.string().optional().nullable(),
});

export const foundationsUpdateSchema = z.object({
  cover_image_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  description: z.string().optional(),
  entity_type: creatorEntityTypeSchema.optional(),
  founded_year: z.number().optional(),
  founder_id: z.string().optional(),
  id: z.string().optional(),
  logo_url: z.string().optional().nullable(),
  metadata: jsonSchema.optional(),
  mission: z.string().optional().nullable(),
  name: z.string().optional(),
  slug: z.string().optional(),
  social_links: jsonSchema.optional(),
  total_campaigns_completed: z.number().optional(),
  total_campaigns_open: z.number().optional(),
  total_donations_received: z.number().optional(),
  updated_at: z.string().optional(),
  vision: z.string().optional().nullable(),
  website_url: z.string().optional().nullable(),
});

export const governanceOptionsRowSchema = z.object({
  contract_option_id: z.number().nullable(),
  created_at: z.string(),
  description: z.string().nullable(),
  downvotes: z.number(),
  id: z.string(),
  image_url: z.string().nullable(),
  project_slug: z.string().nullable(),
  round_id: z.string(),
  title: z.string(),
  total_weight: z.number(),
  updated_at: z.string(),
  upvotes: z.number(),
});

export const governanceOptionsInsertSchema = z.object({
  contract_option_id: z.number().optional().nullable(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  downvotes: z.number().optional(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  project_slug: z.string().optional().nullable(),
  round_id: z.string(),
  title: z.string(),
  total_weight: z.number().optional(),
  updated_at: z.string().optional(),
  upvotes: z.number().optional(),
});

export const governanceOptionsUpdateSchema = z.object({
  contract_option_id: z.number().optional().nullable(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  downvotes: z.number().optional(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  project_slug: z.string().optional().nullable(),
  round_id: z.string().optional(),
  title: z.string().optional(),
  total_weight: z.number().optional(),
  updated_at: z.string().optional(),
  upvotes: z.number().optional(),
});

export const governanceRoundStatusSchema = z.union([
  z.literal("upcoming"),
  z.literal("active"),
  z.literal("ended"),
]);

export const governanceRoundsInsertSchema = z.object({
  contract_round_id: z.number().optional().nullable(),
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  ends_at: z.string(),
  fund_currency: z.string().optional(),
  id: z.string().optional(),
  starts_at: z.string(),
  status: governanceRoundStatusSchema.optional(),
  title: z.string(),
  total_fund_amount: z.number().optional(),
  updated_at: z.string().optional(),
  winner_option_id: z.string().optional().nullable(),
});

export const governanceRoundsUpdateSchema = z.object({
  contract_round_id: z.number().optional().nullable(),
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  ends_at: z.string().optional(),
  fund_currency: z.string().optional(),
  id: z.string().optional(),
  starts_at: z.string().optional(),
  status: governanceRoundStatusSchema.optional(),
  title: z.string().optional(),
  total_fund_amount: z.number().optional(),
  updated_at: z.string().optional(),
  winner_option_id: z.string().optional().nullable(),
});

export const governanceVotesRowSchema = z.object({
  created_at: z.string(),
  id: z.string(),
  nft_tier: z.string(),
  option_id: z.string(),
  round_id: z.string(),
  stellar_address: z.string().nullable(),
  user_id: z.string(),
  vote_type: z.string(),
  vote_weight: z.number(),
});

export const governanceVotesInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  nft_tier: z.string().optional(),
  option_id: z.string(),
  round_id: z.string(),
  stellar_address: z.string().optional().nullable(),
  user_id: z.string(),
  vote_type: z.string(),
  vote_weight: z.number().optional(),
});

export const governanceVotesUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  nft_tier: z.string().optional(),
  option_id: z.string().optional(),
  round_id: z.string().optional(),
  stellar_address: z.string().optional().nullable(),
  user_id: z.string().optional(),
  vote_type: z.string().optional(),
  vote_weight: z.number().optional(),
});

export const kycAdminWhitelistRowSchema = z.object({
  created_at: z.string(),
  created_by: z.string().nullable(),
  id: z.string(),
  notes: z.string().nullable(),
  user_id: z.string(),
});

export const kycAdminWhitelistInsertSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  id: z.string().optional(),
  notes: z.string().optional().nullable(),
  user_id: z.string(),
});

export const kycAdminWhitelistUpdateSchema = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional().nullable(),
  id: z.string().optional(),
  notes: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const kycStatusEnumSchema = z.union([
  z.literal("pending"),
  z.literal("approved"),
  z.literal("rejected"),
  z.literal("verified"),
]);

export const kycVerificationEnumSchema = z.union([
  z.literal("basic"),
  z.literal("enhanced"),
]);

export const kycReviewsInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  notes: z.string().optional().nullable(),
  reviewer_id: z.string().optional().nullable(),
  status: kycStatusEnumSchema,
  updated_at: z.string().optional(),
  user_id: z.string(),
  verification_level: kycVerificationEnumSchema,
});

export const kycReviewsUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  notes: z.string().optional().nullable(),
  reviewer_id: z.string().optional().nullable(),
  status: kycStatusEnumSchema.optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
  verification_level: kycVerificationEnumSchema.optional(),
});

export const milestoneStatusSchema = z.union([
  z.literal("pending"),
  z.literal("completed"),
  z.literal("approved"),
  z.literal("rejected"),
  z.literal("disputed"),
]);

export const milestonesInsertSchema = z.object({
  amount: z.number(),
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  deadline: z.string(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  order_index: z.number(),
  project_id: z.string(),
  status: milestoneStatusSchema.optional(),
  title: z.string(),
});

export const milestonesUpdateSchema = z.object({
  amount: z.number().optional(),
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  deadline: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  order_index: z.number().optional(),
  project_id: z.string().optional(),
  status: milestoneStatusSchema.optional(),
  title: z.string().optional(),
});

export const notificationLogsRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.string(),
  level: z.string(),
  message: z.string(),
  metadata: jsonSchema.nullable(),
  notification_id: z.string().nullable(),
});

export const notificationLogsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  level: z.string(),
  message: z.string(),
  metadata: jsonSchema.optional().nullable(),
  notification_id: z.string().optional().nullable(),
});

export const notificationLogsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  level: z.string().optional(),
  message: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  notification_id: z.string().optional().nullable(),
});

export const notificationPreferencesRowSchema = z.object({
  created_at: z.string().nullable(),
  email: z.boolean().nullable(),
  in_app: z.boolean().nullable(),
  push: z.boolean().nullable(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
});

export const notificationPreferencesInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  email: z.boolean().optional().nullable(),
  in_app: z.boolean().optional().nullable(),
  push: z.boolean().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
});

export const notificationPreferencesUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  email: z.boolean().optional().nullable(),
  in_app: z.boolean().optional().nullable(),
  push: z.boolean().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const notificationDeliveryStatusSchema = z.union([
  z.literal("pending"),
  z.literal("delivered"),
  z.literal("failed"),
]);

export const notificationPrioritySchema = z.union([
  z.literal("low"),
  z.literal("medium"),
  z.literal("high"),
  z.literal("urgent"),
]);

export const notificationTypeSchema = z.union([
  z.literal("info"),
  z.literal("success"),
  z.literal("warning"),
  z.literal("error"),
]);

export const notificationsInsertSchema = z.object({
  body: z.string(),
  created_at: z.string().optional().nullable(),
  data: jsonSchema.optional().nullable(),
  delivery_attempts: z.number().optional().nullable(),
  delivery_status: notificationDeliveryStatusSchema.optional().nullable(),
  expires_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_read: z.boolean().optional().nullable(),
  metadata: jsonSchema.optional().nullable(),
  next_retry_at: z.string().optional().nullable(),
  priority: notificationPrioritySchema.optional(),
  title: z.string(),
  type: notificationTypeSchema.optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
});

export const notificationsUpdateSchema = z.object({
  body: z.string().optional(),
  created_at: z.string().optional().nullable(),
  data: jsonSchema.optional().nullable(),
  delivery_attempts: z.number().optional().nullable(),
  delivery_status: notificationDeliveryStatusSchema.optional().nullable(),
  expires_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_read: z.boolean().optional().nullable(),
  metadata: jsonSchema.optional().nullable(),
  next_retry_at: z.string().optional().nullable(),
  priority: notificationPrioritySchema.optional(),
  title: z.string().optional(),
  type: notificationTypeSchema.optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const userRoleSchema = z.union([
  z.literal("donor"),
  z.literal("creator"),
  z.literal("pending"),
  z.literal("admin"),
  z.literal("kinder"),
  z.literal("kindler"),
]);

export const profilesInsertSchema = z.object({
  bio: z.string().optional().nullable(),
  country: z.string().optional().nullable(),
  created_at: z.string().optional(),
  creator_entity_type: creatorEntityTypeSchema.optional().nullable(),
  display_name: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  external_wallet_address: z.string().optional().nullable(),
  headline: z.string().optional().nullable(),
  id: z.string(),
  image_url: z.string().optional().nullable(),
  next_auth_user_id: z.string().optional().nullable(),
  role: userRoleSchema.optional(),
  slug: z.string().optional().nullable(),
  social_links: jsonSchema.optional(),
  updated_at: z.string().optional(),
  website_url: z.string().optional().nullable(),
});

export const profilesUpdateSchema = z.object({
  bio: z.string().optional().nullable(),
  country: z.string().optional().nullable(),
  created_at: z.string().optional(),
  creator_entity_type: creatorEntityTypeSchema.optional().nullable(),
  display_name: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  external_wallet_address: z.string().optional().nullable(),
  headline: z.string().optional().nullable(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  next_auth_user_id: z.string().optional().nullable(),
  role: userRoleSchema.optional(),
  slug: z.string().optional().nullable(),
  social_links: jsonSchema.optional(),
  updated_at: z.string().optional(),
  website_url: z.string().optional().nullable(),
});

export const projectEscrowsRowSchema = z.object({
  created_at: z.string(),
  escrow_id: z.string(),
  project_id: z.string(),
  updated_at: z.string(),
});

export const projectEscrowsInsertSchema = z.object({
  created_at: z.string().optional(),
  escrow_id: z.string(),
  project_id: z.string(),
  updated_at: z.string().optional(),
});

export const projectEscrowsUpdateSchema = z.object({
  created_at: z.string().optional(),
  escrow_id: z.string().optional(),
  project_id: z.string().optional(),
  updated_at: z.string().optional(),
});

export const projectMemberRoleSchema = z.union([
  z.literal("admin"),
  z.literal("editor"),
  z.literal("advisor"),
  z.literal("community"),
  z.literal("core"),
  z.literal("others"),
]);

export const projectMembersInsertSchema = z.object({
  id: z.string().optional(),
  joined_at: z.string().optional(),
  project_id: z.string(),
  role: projectMemberRoleSchema.optional(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const projectMembersUpdateSchema = z.object({
  id: z.string().optional(),
  joined_at: z.string().optional(),
  project_id: z.string().optional(),
  role: projectMemberRoleSchema.optional(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const projectPitchRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.string(),
  pitch_deck: z.string().nullable(),
  project_id: z.string(),
  story: z.string(),
  title: z.string(),
  updated_at: z.string().nullable(),
  video_url: z.string().nullable(),
});

export const projectPitchInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  pitch_deck: z.string().optional().nullable(),
  project_id: z.string(),
  story: z.string(),
  title: z.string(),
  updated_at: z.string().optional().nullable(),
  video_url: z.string().optional().nullable(),
});

export const projectPitchUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  pitch_deck: z.string().optional().nullable(),
  project_id: z.string().optional(),
  story: z.string().optional(),
  title: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  video_url: z.string().optional().nullable(),
});

export const projectTagRelationshipsRowSchema = z.object({
  project_id: z.string(),
  tag_id: z.string(),
});

export const projectTagRelationshipsInsertSchema = z.object({
  project_id: z.string(),
  tag_id: z.string(),
});

export const projectTagRelationshipsUpdateSchema = z.object({
  project_id: z.string().optional(),
  tag_id: z.string().optional(),
});

export const projectTagsRowSchema = z.object({
  color: z.string(),
  created_at: z.string().nullable(),
  id: z.string(),
  name: z.string(),
  updated_at: z.string().nullable(),
});

export const projectTagsInsertSchema = z.object({
  color: z.string(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string(),
  updated_at: z.string().optional().nullable(),
});

export const projectTagsUpdateSchema = z.object({
  color: z.string().optional(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const projectTeamRowSchema = z.object({
  bio: z.string().nullable(),
  created_at: z.string(),
  full_name: z.string(),
  id: z.string(),
  order_index: z.number(),
  photo_url: z.string().nullable(),
  project_id: z.string(),
  role_title: z.string(),
  updated_at: z.string(),
  years_involved: z.number().nullable(),
});

export const projectTeamInsertSchema = z.object({
  bio: z.string().optional().nullable(),
  created_at: z.string().optional(),
  full_name: z.string(),
  id: z.string().optional(),
  order_index: z.number().optional(),
  photo_url: z.string().optional().nullable(),
  project_id: z.string(),
  role_title: z.string(),
  updated_at: z.string().optional(),
  years_involved: z.number().optional().nullable(),
});

export const projectTeamUpdateSchema = z.object({
  bio: z.string().optional().nullable(),
  created_at: z.string().optional(),
  full_name: z.string().optional(),
  id: z.string().optional(),
  order_index: z.number().optional(),
  photo_url: z.string().optional().nullable(),
  project_id: z.string().optional(),
  role_title: z.string().optional(),
  updated_at: z.string().optional(),
  years_involved: z.number().optional().nullable(),
});

export const projectUpdatesRowSchema = z.object({
  author_id: z.string(),
  content: z.string(),
  created_at: z.string(),
  id: z.string(),
  project_id: z.string(),
  title: z.string(),
  updated_at: z.string(),
});

export const projectUpdatesInsertSchema = z.object({
  author_id: z.string(),
  content: z.string(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  project_id: z.string(),
  title: z.string(),
  updated_at: z.string().optional(),
});

export const projectUpdatesUpdateSchema = z.object({
  author_id: z.string().optional(),
  content: z.string().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  project_id: z.string().optional(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
});

export const projectStatusSchema = z.union([
  z.literal("draft"),
  z.literal("review"),
  z.literal("active"),
  z.literal("paused"),
  z.literal("funded"),
  z.literal("rejected"),
]);

export const projectsInsertSchema = z.object({
  category_id: z.string(),
  created_at: z.string().optional().nullable(),
  current_amount: z.number().optional(),
  description: z.string(),
  development_only: z.boolean().optional(),
  foundation_id: z.string().optional().nullable(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  kinder_count: z.number().optional(),
  kindler_id: z.string(),
  metadata: jsonSchema.optional(),
  min_investment: z.number(),
  percentage_complete: z.number().optional(),
  project_location: z.string(),
  slug: z.string().optional().nullable(),
  social_links: jsonSchema.optional(),
  status: projectStatusSchema.optional(),
  target_amount: z.number(),
  title: z.string(),
  updated_at: z.string().optional().nullable(),
});

export const projectsUpdateSchema = z.object({
  category_id: z.string().optional(),
  created_at: z.string().optional().nullable(),
  current_amount: z.number().optional(),
  description: z.string().optional(),
  development_only: z.boolean().optional(),
  foundation_id: z.string().optional().nullable(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  kinder_count: z.number().optional(),
  kindler_id: z.string().optional(),
  metadata: jsonSchema.optional(),
  min_investment: z.number().optional(),
  percentage_complete: z.number().optional(),
  project_location: z.string().optional(),
  slug: z.string().optional().nullable(),
  social_links: jsonSchema.optional(),
  status: projectStatusSchema.optional(),
  target_amount: z.number().optional(),
  title: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const questTypeSchema = z.union([
  z.literal("multi_region_donation"),
  z.literal("weekly_streak"),
  z.literal("multi_category_donation"),
  z.literal("referral_quest"),
  z.literal("total_donation_amount"),
  z.literal("quest_master"),
]);

export const questDefinitionsInsertSchema = z.object({
  contract_address: z.string().optional().nullable(),
  created_at: z.string().optional(),
  description: z.string(),
  expires_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_active: z.boolean().optional(),
  name: z.string(),
  quest_id: z.number(),
  quest_type: questTypeSchema,
  reward_points: z.number().optional(),
  target_value: z.number(),
  updated_at: z.string().optional(),
});

export const questDefinitionsUpdateSchema = z.object({
  contract_address: z.string().optional().nullable(),
  created_at: z.string().optional(),
  description: z.string().optional(),
  expires_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_active: z.boolean().optional(),
  name: z.string().optional(),
  quest_id: z.number().optional(),
  quest_type: questTypeSchema.optional(),
  reward_points: z.number().optional(),
  target_value: z.number().optional(),
  updated_at: z.string().optional(),
});

export const referralStatusSchema = z.union([
  z.literal("pending"),
  z.literal("onboarded"),
  z.literal("first_donation"),
  z.literal("active"),
]);

export const referralRecordsInsertSchema = z.object({
  contract_address: z.string().optional().nullable(),
  created_at: z.string().optional(),
  first_donation_at: z.string().optional().nullable(),
  id: z.string().optional(),
  onboarded_at: z.string().optional().nullable(),
  referred_id: z.string(),
  referrer_id: z.string(),
  status: referralStatusSchema.optional(),
  total_donations: z.number().optional(),
});

export const referralRecordsUpdateSchema = z.object({
  contract_address: z.string().optional().nullable(),
  created_at: z.string().optional(),
  first_donation_at: z.string().optional().nullable(),
  id: z.string().optional(),
  onboarded_at: z.string().optional().nullable(),
  referred_id: z.string().optional(),
  referrer_id: z.string().optional(),
  status: referralStatusSchema.optional(),
  total_donations: z.number().optional(),
});

export const referrerStatisticsRowSchema = z.object({
  active_referrals: z.number(),
  created_at: z.string(),
  id: z.string(),
  referrer_id: z.string(),
  total_referrals: z.number(),
  total_reward_points: z.number(),
  updated_at: z.string(),
});

export const referrerStatisticsInsertSchema = z.object({
  active_referrals: z.number().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  referrer_id: z.string(),
  total_referrals: z.number().optional(),
  total_reward_points: z.number().optional(),
  updated_at: z.string().optional(),
});

export const referrerStatisticsUpdateSchema = z.object({
  active_referrals: z.number().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  referrer_id: z.string().optional(),
  total_referrals: z.number().optional(),
  total_reward_points: z.number().optional(),
  updated_at: z.string().optional(),
});

export const userFollowsRowSchema = z.object({
  created_at: z.string(),
  follower_id: z.string(),
  following_id: z.string(),
});

export const userFollowsInsertSchema = z.object({
  created_at: z.string().optional(),
  follower_id: z.string(),
  following_id: z.string(),
});

export const userFollowsUpdateSchema = z.object({
  created_at: z.string().optional(),
  follower_id: z.string().optional(),
  following_id: z.string().optional(),
});

export const userNftsRowSchema = z.object({
  contract_address: z.string(),
  created_at: z.string(),
  evolved_at: z.string().nullable(),
  id: z.string(),
  image_ipfs_hash: z.string().nullable(),
  metadata_ipfs_hash: z.string().nullable(),
  minted_at: z.string(),
  stellar_address: z.string(),
  tier: z.string(),
  token_id: z.number(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const userNftsInsertSchema = z.object({
  contract_address: z.string(),
  created_at: z.string().optional(),
  evolved_at: z.string().optional().nullable(),
  id: z.string().optional(),
  image_ipfs_hash: z.string().optional().nullable(),
  metadata_ipfs_hash: z.string().optional().nullable(),
  minted_at: z.string().optional(),
  stellar_address: z.string(),
  tier: z.string().optional(),
  token_id: z.number(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const userNftsUpdateSchema = z.object({
  contract_address: z.string().optional(),
  created_at: z.string().optional(),
  evolved_at: z.string().optional().nullable(),
  id: z.string().optional(),
  image_ipfs_hash: z.string().optional().nullable(),
  metadata_ipfs_hash: z.string().optional().nullable(),
  minted_at: z.string().optional(),
  stellar_address: z.string().optional(),
  tier: z.string().optional(),
  token_id: z.number().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const userQuestProgressRowSchema = z.object({
  completed_at: z.string().nullable(),
  created_at: z.string(),
  current_value: z.number(),
  id: z.string(),
  is_completed: z.boolean(),
  quest_id: z.number(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const userQuestProgressInsertSchema = z.object({
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  current_value: z.number().optional(),
  id: z.string().optional(),
  is_completed: z.boolean().optional(),
  quest_id: z.number(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const userQuestProgressUpdateSchema = z.object({
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  current_value: z.number().optional(),
  id: z.string().optional(),
  is_completed: z.boolean().optional(),
  quest_id: z.number().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const streakPeriodSchema = z.union([
  z.literal("weekly"),
  z.literal("monthly"),
]);

export const userStreaksInsertSchema = z.object({
  contract_address: z.string().optional().nullable(),
  created_at: z.string().optional(),
  current_streak: z.number().optional(),
  id: z.string().optional(),
  last_donation_timestamp: z.string().optional().nullable(),
  longest_streak: z.number().optional(),
  period: streakPeriodSchema,
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const userStreaksUpdateSchema = z.object({
  contract_address: z.string().optional().nullable(),
  created_at: z.string().optional(),
  current_streak: z.number().optional(),
  id: z.string().optional(),
  last_donation_timestamp: z.string().optional().nullable(),
  longest_streak: z.number().optional(),
  period: streakPeriodSchema.optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const waitlistInterestsRowSchema = z.object({
  category_id: z.string().nullable(),
  consent: z.boolean(),
  created_at: z.string(),
  email: z.string().nullable(),
  id: z.string(),
  location: z.string().nullable(),
  name: z.string(),
  project_description: z.string().nullable(),
  project_name: z.string().nullable(),
  role: z.string(),
  source: z.string().nullable(),
});

export const waitlistInterestsInsertSchema = z.object({
  category_id: z.string().optional().nullable(),
  consent: z.boolean().optional(),
  created_at: z.string().optional(),
  email: z.string().optional().nullable(),
  id: z.string().optional(),
  location: z.string().optional().nullable(),
  name: z.string(),
  project_description: z.string().optional().nullable(),
  project_name: z.string().optional().nullable(),
  role: z.string(),
  source: z.string().optional().nullable(),
});

export const waitlistInterestsUpdateSchema = z.object({
  category_id: z.string().optional().nullable(),
  consent: z.boolean().optional(),
  created_at: z.string().optional(),
  email: z.string().optional().nullable(),
  id: z.string().optional(),
  location: z.string().optional().nullable(),
  name: z.string().optional(),
  project_description: z.string().optional().nullable(),
  project_name: z.string().optional().nullable(),
  role: z.string().optional(),
  source: z.string().optional().nullable(),
});

export const questStatusSchema = z.union([
  z.literal("active"),
  z.literal("completed"),
  z.literal("expired"),
]);

export const commentsRowSchema = z.object({
  author_id: z.string(),
  content: z.string(),
  created_at: z.string().nullable(),
  id: z.string(),
  metadata: jsonSchema,
  parent_comment_id: z.string().nullable(),
  project_id: z.string().nullable(),
  project_update_id: z.string().nullable(),
  type: commentTypeSchema,
  updated_at: z.string().nullable(),
});

export const escrowContractsRowSchema = z.object({
  amount: z.number(),
  completed_at: z.string().nullable(),
  contract_id: z.string(),
  contribution_id: z.string(),
  created_at: z.string().nullable(),
  current_state: escrowStatusTypeSchema,
  engagement_id: z.string(),
  id: z.string(),
  metadata: jsonSchema.nullable(),
  payer_address: z.string(),
  platform_fee: z.number(),
  project_id: z.string(),
  receiver_address: z.string(),
  updated_at: z.string().nullable(),
});

export const foundationsRowSchema = z.object({
  cover_image_url: z.string().nullable(),
  created_at: z.string(),
  description: z.string(),
  entity_type: creatorEntityTypeSchema,
  founded_year: z.number(),
  founder_id: z.string(),
  id: z.string(),
  logo_url: z.string().nullable(),
  metadata: jsonSchema,
  mission: z.string().nullable(),
  name: z.string(),
  slug: z.string(),
  social_links: jsonSchema,
  total_campaigns_completed: z.number(),
  total_campaigns_open: z.number(),
  total_donations_received: z.number(),
  updated_at: z.string(),
  vision: z.string().nullable(),
  website_url: z.string().nullable(),
});

export const governanceRoundsRowSchema = z.object({
  contract_round_id: z.number().nullable(),
  created_at: z.string(),
  created_by: z.string().nullable(),
  description: z.string().nullable(),
  ends_at: z.string(),
  fund_currency: z.string(),
  id: z.string(),
  starts_at: z.string(),
  status: governanceRoundStatusSchema,
  title: z.string(),
  total_fund_amount: z.number(),
  updated_at: z.string(),
  winner_option_id: z.string().nullable(),
});

export const kycReviewsRowSchema = z.object({
  created_at: z.string(),
  id: z.string(),
  notes: z.string().nullable(),
  reviewer_id: z.string().nullable(),
  status: kycStatusEnumSchema,
  updated_at: z.string(),
  user_id: z.string(),
  verification_level: kycVerificationEnumSchema,
});

export const milestonesRowSchema = z.object({
  amount: z.number(),
  completed_at: z.string().nullable(),
  created_at: z.string().nullable(),
  deadline: z.string(),
  description: z.string().nullable(),
  id: z.string(),
  order_index: z.number(),
  project_id: z.string(),
  status: milestoneStatusSchema,
  title: z.string(),
});

export const notificationsRowSchema = z.object({
  body: z.string(),
  created_at: z.string().nullable(),
  data: jsonSchema.nullable(),
  delivery_attempts: z.number().nullable(),
  delivery_status: notificationDeliveryStatusSchema.nullable(),
  expires_at: z.string().nullable(),
  id: z.string(),
  is_read: z.boolean().nullable(),
  metadata: jsonSchema.nullable(),
  next_retry_at: z.string().nullable(),
  priority: notificationPrioritySchema,
  title: z.string(),
  type: notificationTypeSchema,
  updated_at: z.string().nullable(),
  user_id: z.string(),
});

export const profilesRowSchema = z.object({
  bio: z.string().nullable(),
  country: z.string().nullable(),
  created_at: z.string(),
  creator_entity_type: creatorEntityTypeSchema.nullable(),
  display_name: z.string().nullable(),
  email: z.string().nullable(),
  external_wallet_address: z.string().nullable(),
  headline: z.string().nullable(),
  id: z.string(),
  image_url: z.string().nullable(),
  next_auth_user_id: z.string().nullable(),
  role: userRoleSchema,
  slug: z.string().nullable(),
  social_links: jsonSchema,
  updated_at: z.string(),
  website_url: z.string().nullable(),
});

export const projectMembersRowSchema = z.object({
  id: z.string(),
  joined_at: z.string(),
  project_id: z.string(),
  role: projectMemberRoleSchema,
  title: z.string(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const projectsRowSchema = z.object({
  category_id: z.string(),
  created_at: z.string().nullable(),
  current_amount: z.number(),
  description: z.string(),
  development_only: z.boolean(),
  foundation_id: z.string().nullable(),
  id: z.string(),
  image_url: z.string().nullable(),
  kinder_count: z.number(),
  kindler_id: z.string(),
  metadata: jsonSchema,
  min_investment: z.number(),
  percentage_complete: z.number(),
  project_location: z.string(),
  slug: z.string().nullable(),
  social_links: jsonSchema,
  status: projectStatusSchema,
  target_amount: z.number(),
  title: z.string(),
  updated_at: z.string().nullable(),
});

export const questDefinitionsRowSchema = z.object({
  contract_address: z.string().nullable(),
  created_at: z.string(),
  description: z.string(),
  expires_at: z.string().nullable(),
  id: z.string(),
  is_active: z.boolean(),
  name: z.string(),
  quest_id: z.number(),
  quest_type: questTypeSchema,
  reward_points: z.number(),
  target_value: z.number(),
  updated_at: z.string(),
});

export const referralRecordsRowSchema = z.object({
  contract_address: z.string().nullable(),
  created_at: z.string(),
  first_donation_at: z.string().nullable(),
  id: z.string(),
  onboarded_at: z.string().nullable(),
  referred_id: z.string(),
  referrer_id: z.string(),
  status: referralStatusSchema,
  total_donations: z.number(),
});

export const userStreaksRowSchema = z.object({
  contract_address: z.string().nullable(),
  created_at: z.string(),
  current_streak: z.number(),
  id: z.string(),
  last_donation_timestamp: z.string().nullable(),
  longest_streak: z.number(),
  period: streakPeriodSchema,
  updated_at: z.string(),
  user_id: z.string(),
});
