export enum AuthErrorType {
	INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
	EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
	INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN',
	WEAK_PASSWORD = 'WEAK_PASSWORD',
	EMAIL_TAKEN = 'EMAIL_TAKEN',
	EXPIRED_CODE = 'EXPIRED_CODE',
	INVALID_CODE = 'INVALID_CODE',
	NO_CODE_PROVIDED = 'NO_CODE_PROVIDED',
	SESSION_EXPIRED = 'SESSION_EXPIRED',
	RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
	UNAUTHORIZED = 'UNAUTHORIZED',
	SERVER_ERROR = 'SERVER_ERROR',
}

export interface AuthResponse {
	success: boolean
	message: string
	data?: Record<string, unknown>
	error?: string
	redirect?: string
}
