import type { Creator, Project } from '~/lib/types/projects.types'

export const featuredProjects: Project[] = [
	{
		id: '2',
		title: 'Solar Power for Communities',
		description: 'Sustainable energy solutions for remote villages',
		location: 'Remote Villages, India',
		current_amount: 120000,
		target_amount: 100000,
		kinder_count: 850,
		image_url: '/images/renewable-energy.webp',
		milestones: 4,
		completed_milestones: 4,
		creator: {
			id: 2,
			name: 'Sarah Chen',
			image: '/images/nft7.png',
			verified: true,
			completed_projects: 3,
		},
		trending: false,
		featured: true,
		categories: ['energy'],
		min_investment: 0,
		created_at: '2023-09-22T00:00:00Z',
		tags: [],
	},
	{
		id: '1',
		title: 'Clean Water Initiative',
		description: 'Providing clean water access to rural communities',
		location: 'Rural Schools, Kenya',
		current_amount: 75000,
		target_amount: 50000,
		kinder_count: 1200,
		image_url: '/images/water.webp',
		categories: ['water'],
		milestones: 3,
		completed_milestones: 3,
		creator: {
			id: 1,
			name: 'John Doe',
			image: '/images/nft8.png',
			verified: true,
			completed_projects: 5,
		},
		trending: true,
		featured: true,
		min_investment: 0,
		created_at: '2023-08-22T00:00:00Z',
		tags: [],
	},
	{
		id: '3',
		title: 'Education Technology Access',
		description: 'Bringing modern learning tools to underserved schools',
		location: 'Urban Schools, Brazil',
		current_amount: 45000,
		target_amount: 40000,
		kinder_count: 1600,
		image_url: '/images/education.webp',
		milestones: 3,
		completed_milestones: 3,
		created_at: '2023-11-22T00:00:00Z',
		creator: {
			id: 3,
			name: 'Maria Rodriguez',
			image: '/images/nft6.png',
			verified: true,
			completed_projects: 4,
		},
		trending: true,
		featured: false,
		categories: ['education'],
		min_investment: 0,
		tags: [],
	},
]

export const featuredCreators: Creator[] = [
	{
		id: 1,
		name: 'Alice Green',
		role: 'Social Entrepreneur',
		image: '/images/nft5.png',
		total_current_amount: 250000,
		completed_projects: 8,
		followers: 1200,
		recent_project: 'Sustainable Agriculture Initiative',
		verified: true,
	},
	{
		id: 2,
		name: 'David Kumar',
		role: 'Environmental Activist',
		image: '/images/nft4.png',
		total_current_amount: 180000,
		completed_projects: 6,
		followers: 950,
		recent_project: 'Ocean Cleanup Campaign',
		verified: true,
	},
	{
		id: 3,
		name: 'Sophie Chen',
		role: 'Education Advocate',
		image: '/images/nft3.png',
		total_current_amount: 150000,
		completed_projects: 5,
		followers: 800,
		recent_project: 'Digital Learning for All',
		verified: true,
	},
]
