import { Project } from "~/lib/types/projects.types"


export const featuredProjects: Project[] = [
	{
		id: 1,
		title: 'Clean Water Initiative',
		description: 'Providing clean water access to rural communities',
		location: 'Rural Schools, Kenya',
		raised: 75000,
		goal: 50000,
		donors: 1200,
		image: '/images/water.webp',
		category: 'Environment',
		milestones: 3,
		completedMilestones: 3,
		creator: {
			id: 1,
			name: 'John Doe',
			image: '/images/nft8.png',
			verified: true,
			completedProjects: 5,
		},
		trending: true,
		featured: true,
	},
	{
		id: 2,
		title: 'Solar Power for Communities',
		description: 'Sustainable energy solutions for remote villages',
		location: 'Remote Villages, India',
		raised: 120000,
		goal: 100000,
		donors: 850,
		image: '/images/renewable-energy.webp',
		category: 'Energy',
		milestones: 4,
		completedMilestones: 4,
		creator: {
			id: 2,
			name: 'Sarah Chen',
			image: '/images/nft7.png',
			verified: true,
			completedProjects: 3,
		},
		trending: false,
		featured: true,
	},
	{
		id: 3,
		title: 'Education Technology Access',
		description: 'Bringing modern learning tools to underserved schools',
		location: 'Urban Schools, Brazil',
		raised: 45000,
		goal: 40000,
		donors: 600,
		image: '/images/education.webp',
		category: 'Education',
		milestones: 3,
		completedMilestones: 3,
		creator: {
			id: 3,
			name: 'Maria Rodriguez',
			image: '/images/nft6.png',
			verified: true,
			completedProjects: 4,
		},
		trending: true,
		featured: false,
	},
]

export const featuredCreators: Creator[] = [
	{
		id: 1,
		name: 'Alice Green',
		role: 'Social Entrepreneur',
		image: '/images/nft5.png',
		totalRaised: 250000,
		completedProjects: 8,
		followers: 1200,
		recentProject: 'Sustainable Agriculture Initiative',
		verified: true,
	},
	{
		id: 2,
		name: 'David Kumar',
		role: 'Environmental Activist',
		image: '/images/nft4.png',
		totalRaised: 180000,
		completedProjects: 6,
		followers: 950,
		recentProject: 'Ocean Cleanup Campaign',
		verified: true,
	},
	{
		id: 3,
		name: 'Sophie Chen',
		role: 'Education Advocate',
		image: '/images/nft3.png',
		totalRaised: 150000,
		completedProjects: 5,
		followers: 800,
		recentProject: 'Digital Learning for All',
		verified: true,
	},
]
