import type { Creator, Project } from '~/lib/types/projects.types'

export const featuredProjects: Project[] = [
	{
		id: '2',
		title: 'Solar Power for Communities',
		description: 'Sustainable energy solutions for remote villages',
		location: 'Remote Villages, India',
		currentAmount: 120000,
		targetAmount: 100000,
		investors: 850,
		image: '/images/renewable-energy.webp',
		milestones: 4,
		completedMilestones: 4,
		creator: {
			id: 2,
			name: 'Sarah Chen',
			image: '/images/nft7.png',
			verified: true,
			completedProjects: 3,
		},
		trending: false,
		featured: true,
		categories: ['energy'],
		minInvestment: 0,
		createdAt: '2023-09-22T00:00:00Z',
		tags: [],
	},
	{
		id: '1',
		title: 'Clean Water Initiative',
		description: 'Providing clean water access to rural communities',
		location: 'Rural Schools, Kenya',
		currentAmount: 75000,
		targetAmount: 50000,
		investors: 1200,
		image: '/images/water.webp',
		categories: ['water'],
		milestones: 3,
		completedMilestones: 3,
		creator: {
			id: 1,
			name: 'John Doe',
			image: '/images/nft8.png',
			verified: true,
			completedProjects: 5,
		},
		trending: true,
		featured: true,
		minInvestment: 0,
		createdAt: '2023-08-22T00:00:00Z',
		tags: [],
	},
	{
		id: '3',
		title: 'Education Technology Access',
		description: 'Bringing modern learning tools to underserved schools',
		location: 'Urban Schools, Brazil',
		currentAmount: 45000,
		targetAmount: 40000,
		investors: 1600,
		image: '/images/education.webp',
		milestones: 3,
		completedMilestones: 3,
		createdAt: '2023-11-22T00:00:00Z',
		creator: {
			id: 3,
			name: 'Maria Rodriguez',
			image: '/images/nft6.png',
			verified: true,
			completedProjects: 4,
		},
		trending: true,
		featured: false,
		categories: ['education'],
		minInvestment: 0,
		tags: [],
	},
]

export const featuredCreators: Creator[] = [
	{
		id: 1,
		name: 'Alice Green',
		role: 'Social Entrepreneur',
		image: '/images/nft5.png',
		totalCurrentAmount: 250000,
		completedProjects: 8,
		followers: 1200,
		recentProject: 'Sustainable Agriculture Initiative',
		verified: true,
	},
	{
		id: 2,
		name: 'David Kumar',
		role: 'Environmental Activist',
		image: '/images/nft4.png',
		totalCurrentAmount: 180000,
		completedProjects: 6,
		followers: 950,
		recentProject: 'Ocean Cleanup Campaign',
		verified: true,
	},
	{
		id: 3,
		name: 'Sophie Chen',
		role: 'Education Advocate',
		image: '/images/nft3.png',
		totalCurrentAmount: 150000,
		completedProjects: 5,
		followers: 800,
		recentProject: 'Digital Learning for All',
		verified: true,
	},
]
